spring:
  config:
    activate:
      on-profile: "datasource"

  datasource:
    driver-class-name:
    url: jdbc:mysql://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3309}/healther?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:}

